P-Room/src/main/java/com/yejun/proom/entity/Person.java
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
Person 엔터티 생성
MySQL에서 User라는 단어가 예약어로 들어감에 따라 Person으로 교체 후 작성
resolves #
=> Create Person Entity

P-Room/src/main/java/com/yejun/proom/dto/response/PersonResponseDTO.java, P-Room/src/main/java/com/yejun/proom/entity/Person.java, P-Room/src/main/java/com/yejun/proom/repository/PersonRepository.java, P-Room/src/main/resources/application.properties
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
Person 엔터티를 위한 Repo, DTO 등 작성
resolves #
=> Create Person Repo

src/components/Button.tsx, src/components/CustomDropdown.tsx, src/components/HashTag.tsx, src/components/ResumeDetail.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 이전 PR에서 빠진 부분 보완 후 merge
=> [MERGE] : 이전에 작성됐던 자기소개서 작성 페이지 컴포넌트 미완성 부분 해결 및 merge

P-Room/src/main/java/com/yejun/proom/entity/Person.java, P-Room/src/main/java/com/yejun/proom/repository/PersonRepository.java, P-Room/src/main/java/com/yejun/proom/service/PersonService.java
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
Person Entity에 대한 Service까지 작성
resolves #
=> [FEAT] : PersonService 작성 및 코드 변경

package.json, pnpm-lock.yaml, public/icons/resume-title.svg, src/app/global.css, src/app/page.tsx, src/components/Calendar.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- react-calendar를 이용한 달력 구현
- 현재 더미 데이터로 공고 목록을 리스트 렌더링
- 이후 종료일에 맞춰 출력할 예정
=> [MERGE] : 달력 틀 구현 및 병합

src/app/global.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- react-calendar를 이용한 달력 구현
- 현재 더미 데이터로 공고 목록을 리스트 렌더링
- 이후 종료일에 맞춰 출력할 예정
=> [MERGE] : 스타일 지정 파일 재설정 후 병합

src/components/Header.tsx, src/components/HeaderModal.tsx, src/components/LoggedInHeader.tsx, src/components/LoggedOutHeader.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 현재 모달 구현은 됐지만 이벤트는 들어가지 않은 상황
=> [MERGE] : 헤더의 모바일 반응형 스타일링 구현 및 모달 구현

src/app/404/page.tsx, src/app/not-found.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 오류 시 나타낼 fallback UI구현
=> [MERGE] : fallback UI 구현 및 병합

src/components/KakaoLoginButton.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
=> [MERGE] : 카카오 로그인 확인 배포를 위한 테스트

src/lib/axios.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
=> [FEAT] : withCredentials 속성을 추가하여 CORS 오류 해결

src/components/KakaoLoginRedirection.tsx
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
=> [FEAT] : fetch -> axios 방식으로 변경 및 통신 주소 변경

src/components/KakaoLoginRedirection.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [FEAT] : 자체적인 redirect 삭제

src/components/KakaoLoginRedirection.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [MERGE] : 로그인 테스트를 위한 머지

src/components/KakaoLoginRedirect.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [FEAT] : KakaoLoginRedirect 코드 살리기

src/components/Header.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [FEAT] : 딜레이 함수 제작 후 통신 전에 강제적으로 1초 대기시키기

src/components/Header.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [FEAT] : 대기 함수 수정

src/components/Calendar.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [TEST] : 임시방편으로 console.log를 확인해보기 위한 커밋

src/components/Calendar.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [TEST ] : 콘솔창 확인용 커밋

src/components/Calendar.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> [FEAT] : content 출력 확인

src/components/Calendar.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 데이터 확인 용 커밋

src/components/Calendar.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 날짜를 불러와 리스트를 갱신하는 로직 구현

src/components/Calendar.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 더미 데이터에서 실제 데이터로 변경

src/components/Calendar.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 데이터 타입 변경 후 재커밋

src/components/Calendar.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 달력 최종 수정(일듯)
